'use client';

/**
 * Small "AI" badge shown on components whose content is generated by the
 * AI layer (one-line reasons, "more like this" picks). Hovering reveals a
 * tooltip explaining that an API key must be set to enable the feature.
 */
export function AiBadge({ className = '' }: { className?: string }) {
  return (
    <span
      className={`group/ai relative inline-flex shrink-0 ${className}`}
      aria-label="AI-generated — requires an API key"
    >
      <span className="inline-flex items-center rounded-md bg-gradient-to-r from-violet-500/25 to-fuchsia-500/25 px-1.5 py-0.5 text-[9px] font-bold uppercase tracking-widest text-violet-300 ring-1 ring-violet-400/40">
        AI
      </span>
      {/* Tooltip */}
      <span
        role="tooltip"
        className="pointer-events-none absolute bottom-full left-1/2 z-50 mb-1.5 hidden -translate-x-1/2 whitespace-nowrap rounded-lg bg-black/95 px-2.5 py-1.5 text-[10px] font-normal normal-case tracking-normal text-zinc-200 shadow-xl ring-1 ring-white/10 group-hover/ai:block"
      >
        Set an OpenAI API key to enable AI
      </span>
    </span>
  );
}